stages:
  - packaging
  - build_docker_image
default:
  image: maven:3.9.5-openjdk-21

variables:
  MAVEN_OPIS: "-Dmaven.repo.local=/home/pro12x/.m2/repository"
run unit test and package:
  inherit:
    default: true
    variables: true
  stage: packaging
  script:
    - mvn clean package -Dmaven.test.skip
  artifacts:
    paths:
      - target/*.jar
  cache:
    paths:
      - .m2/repository

build docker image:
  image: docker:latest
  stage: build_docker_image
  inherit:
    default: false
    variables: false
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_USER/cicd:1.0 .
    - docker save $DOCKER_USER/cicd > cicd
    - docker login -u $DOCKER_USER -p $DOCKER_TOKEN
    - docker push $DOCKER_USER/cicd:1.0
  artifacts:
    paths:
      - cicd
  when: manual