version: '3.9'

services:

  app-dockervolume-backend:
    image: dockervolume-backend:1.0
    container_name: container-dockervolume-backend
    ports:
      - 8000:8000
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      directoryDatas: /app/data/
    volumes:
      - ./datas:/app/data

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cicd
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  datas:
  postgres_data: